export { default as roleRoute } from './roleRoute.js';
export { default as userRoute } from './userRoute.js';
export { default as functionaryRoute } from './functionaryRoute.js';
export { default as subjectRoute } from './subjectRoute.js';
export { default as preRegistrationRoute } from './preRegistrationRoute.js';
export { default as fileRoute } from './fileRoute.js';
export { default as applicationRoute } from './applicationRoute.js';
export { default as appointmentRoute } from './appointmentRoute.js';
export { default as studentRoute } from './studentRoute.js';
export { default as caregiverRoute } from './caregiverRoute.js';
export { default as groupRoute } from './groupRoute.js';
export {default as classRoute} from './classRoute.js';
export {default as gradeRoute} from './gradeRoute.js';
export {default as timetableRoute} from './timetableRoute.js';
export {default as authRoute} from './authRoute.js';
export { default as loanRoute } from './loanRoute.js';
export { default as flawRoute } from './flawRoute.js';
export { default as studentSupplieRoute } from './studentSupplieRoute.js';
export { default as categorySupplieRoute } from './categorySupplieRoute.js';
export { default as institutionalSupplieRoute } from './institutionalSupplieRoute.js';