const encargados = [
    {
        //1
        "id":"222222222",
        "nombre":"Juan Carlos",
        "apellido1":"Perez",
        "apellido2":"Gonzalez",
    },
    {
        //2
        "id":"112345678",
        "nombre":"Jose",
        "apellido1":"Perez",
        "apellido2":"Gonzalez",
    },
    {
        //3
        "id":"111234567",
        "nombre":"Maria",
        "apellido1":"Vargas",
        "apellido2":"Alcocer",
    },
    {
        //4
        "id":"111123456",
        "nombre":"Ana",
        "apellido1":"Vallejos",
        "apellido2":"Villafuerte",
    },
    {
        //5
        "id":"111112345",
        "nombre":"Luis",
        "apellido1":"Vallejos",
        "apellido2":"Xirinachs",
    },
    {
        //6
        "id":"111111234",
        "nombre":"Gonzalo",
        "apellido1":"Gonzalez",
        "apellido2":"Gonzalez",
    },
    {
        //7
        "id":"111111123",
        "nombre":"Maria",
        "apellido1":"Fernandez",
        "apellido2":"Zamora",
    },
    {
        //8
        "id":"111111112",
        "nombre":"Ana",
        "apellido1":"Porras",
        "apellido2":"Hior",
    },
    {
        //9
        "id":"111111121",
        "nombre":"Luis",
        "apellido1":"Perez",
        "apellido2":"Jimenez",
    },
    {
        //10
        "id":"111111211",
        "nombre":"Oscar Omar",
        "apellido1":"Tencio",
        "apellido2":"Ramirez",
    },
    {
        //11
        "id":"111112111",
        "nombre":"Fernando Andres",
        "apellido1":"Hernandez",
        "apellido2":"Brenes",
    },
    {
        //12
        "id":"111121111",
        "nombre":"karen",
        "apellido1":"Perez",
        "apellido2":"Gonzalez",
    },
    {
        //13
        "id":"111211111",
        "nombre":"Valeria",
        "apellido1":"Vargas",
        "apellido2":"Alcocer",
    },
    {
        //14
        "id":"112111111",
        "nombre":"Jorge",
        "apellido1":"Moraga",
        "apellido2":"Sung",
    },
    {
        //15
        "id":"121111111",
        "nombre":"Natalia",
        "apellido1":"Quesada",
        "apellido2":"Wong",
    },
    {
        //16
        "id":"211111111",
        "nombre":"Elizabeth",
        "apellido1":"Rojas",
        "apellido2":"Tencio",
    },
    {
        //17
        "id":"426920101",
        "nombre":"Yorleny",
        "apellido1":"Umaña",
        "apellido2":"Iglesias",
    },
    {
        //18
        "id":"705726390",
        "nombre":"Oscar",
        "apellido1":"Pereñaranda",
        "apellido2":"Alvarado",
    },
    {
        //19
        "id":"106270739",
        "nombre":"Sandra",
        "apellido1":"Diaz",
        "apellido2":"Fernandez",
    },
    {
        //20
        "id":"322087388",
        "nombre":"Gustavo",
        "apellido1":"Hernandez",
        "apellido2":"Jimenez",
    },
    {
        //21
        "id":"272242415",
        "nombre":"Katherine",
        "apellido1":"Lopez",
        "apellido2":"Ñañez",
    },
    {
        //22
        "id":"205460219",
        "nombre":"Zoila",
        "apellido1":"Xirinachs",
        "apellido2":"Villafuerte",
    },
    {
        //23
        "id":"302148735",
        "nombre":"Cristian",
        "apellido1":"Villafuerte",
        "apellido2":"Brenes",
    },
    {
        //24
        "id":"605468319",
        "nombre":"Natalia",
        "apellido1":"Mora",
        "apellido2":"Quesada",
    },
    {
        //25
        "id":"481320101",
        "nombre":"Wendy Elizabeth",
        "apellido1":"Rojas",
        "apellido2":"Tencio",
    },
    {
        //26
        "id":"563636347",
        "nombre":"Yorleny Ujena",
        "apellido1":"Umaña",
        "apellido2":"Iglesias",
    },
    {
        //27
        "id":"506270799",
        "nombre":"Oscar Pereñaranda",
        "apellido1":"Alvarado",
        "apellido2":"Soto",
    },
    {
        //28
        "id":"555270739",
        "nombre":"Sandra",
        "apellido1":"Diaz",
        "apellido2":"Fernandez",
    },
    {
        //29
        "id":"522080388",
        "nombre":"Gustavo Adolfo",
        "apellido1":"Hernandez",
        "apellido2":"Jimenez",
    },
    {
        //30
        "id":"572242410",
        "nombre":"Katherine",
        "apellido1":"Lopez",
        "apellido2":"Ñañez",
    },
    {
        //31
        "id":"505110219",
        "nombre":"Zoila",
        "apellido1":"Xirinachs",
        "apellido2":"Villafuerte",
    },
    {
        //32
        "id":"502040735",
        "nombre":"Cristian",
        "apellido1":"Villafuerte",
        "apellido2":"Brenes",
    },
    {
        //33
        "id":"605462319",
        "nombre":"Natalia",
        "apellido1":"Mora",
        "apellido2":"Quesada",
    },
    {
        //34
        "id":"481990101",
        "nombre":"Wendy Damaris",
        "apellido1":"Xirinachs",
        "apellido2":"Zamora",
    }


]

export default encargados;