const functionaries = [
	{
		functionaryId: "111111111",
		name: "Luis Carlos",
		middleName: "karen",
		lastName: "Perez",
		lastName2: "Gonzalez",
		birthDate: "1990-01-01",
		age: "  ",
		gender: "M",
        address: "calle x, avenida, colonia d, en el cantón de Santa Cruz",
		userName: "Luis",
	},
	{
		functionaryId: "712345679",
		name: "Juan",
		middleName: "karen",
		lastName: "Vargas",
		lastName2: "Alcocer",
		birthDate: "1990-01-01",
		age: "  ",
		gender: "M",
        address: "calle x, avenida, colonia d, en el cantón de Santa Cruz",
		userName: "Juan",
	},
	{
		//maestra
		functionaryId: "712345678",
		name: "Patricia",
		middleName: "karen",
		lastName: "Vargas",
		lastName2: "Alcocer",
		birthDate: "1990-01-01",
		age: "  ",
		gender: "M",
        address: "calle x, avenida, colonia d, en el cantón de Santa Cruz",
		userName: "Patricia_Master",
	},
	{
		//maestra
		functionaryId: "712345677",
		name: "Maria",
		middleName: "karen",
		lastName: "Vargas",
		lastName2: "Alcocer",
		birthDate: "1990-01-01",
		age: "  ",
		gender: "F",
        address: "calle x, avenida, colonia d, en el cantón de Santa Cruz",
		userName: "Maria_Maestra",
	},
	{
		//maestra
		functionaryId: "712345676",
		name: "Ana",
		middleName: "karen",
		lastName: "Vallejos",
		lastName2: "Villafuerte",
		birthDate: "1990-01-01",
		age: "  ",
		gender: "F",
        address: "calle x, avenida, colonia d, en el cantón de Santa Cruz",
		userName: "Ana_Maestra",
	},
	{
		//maestro
		functionaryId: "712345675",
		name: "Luicito",
		middleName: "karen",
		lastName: "Vallejos",
		lastName2: "Villafuerte",
		birthDate: "1990-01-01",
		age: "  ",
		gender: "M",
        address: "calle x, avenida, colonia d, en el cantón de Santa Cruz",
		userName: "Luis_Maestro",
	},
	{
		//maestro
		functionaryId: "712345674",
		name: "Hector Guillermo",
		middleName: "karen",
		lastName: "Yglesias",
		lastName2: "Iglesias",
		birthDate: "1999-01-06",
		age: "  ",
		gender: "M",
        address: "calle x, avenida, colonia d, en el cantón de Santa Cruz",
		userName: "Hector_Maestro",
	},
	{
		//maestro
		functionaryId: "712345443",
		name: "Karla Wendy",
		middleName: "karen",
		lastName: "Wong",
		lastName2: "Wong",
		birthDate: "2000-08-27",
		age: "  ",
		gender: "F",
        address: "calle x, avenida, colonia d, en el cantón de Santa Cruz",
		userName: "Karla_Maestra",
	},
];

export default functionaries;
