const groups = [
	{
		section: "1-1",
		grade: "primero",
		cycle: "I",
		classRoom: "A",
		shift: "vespertino",
		functionaryId: "712345443",
	},
	{
		section: "1-2",
		grade: "primero",
		cycle: "I",
		classRoom: "A",
		shift: "matutino",
		functionaryId: "712345443",
	},
	{
		section: "2-1",
		grade: "segundo",
		cycle: "I",
		classRoom: "B",
		shift: "vespertino",
		functionaryId: "712345674",
	},
	{
		section: "2-2",
		grade: "segundo",
		cycle: "I",
		classRoom: "B",
		shift: "matutino",
		functionaryId: "712345674",
	},
	{
		section: "3-1",
		grade: "tercero",
		cycle: "I",
		classRoom: "C",
		shift: "vespertino",
		functionaryId: "712345675",
	},
	{
		section: "3-2",
		grade: "tercero",
		cycle: "I",
		classRoom: "C",
		shift: "matutino",
		functionaryId: "712345675",
	},
	{
		section: "4-1",
		grade: "cuarto",
		cycle: "II",
		classRoom: "D",
		shift: "vespertino",
		functionaryId: "712345676",
	},
	{
		section: "4-2",
		grade: "cuarto",
		cycle: "II",
		classRoom: "D",
		shift: "matutino",
		functionaryId: "712345676",
	},
	{
		section: "5-1",
		grade: "quinto",
		cycle: "II",
		classRoom: "E",
		shift: "vespertino",
		horarioId: "9",
		functionaryId: "712345677",
	},
	{
		section: "5-2",
		grade: "quinto",
		cycle: "II",
		classRoom: "E",
		shift: "matutino",
		horarioId: "10",
		functionaryId: "712345677",
	},
	{
		section: "6-1",
		grade: "sexto",
		cycle: "II",
		classRoom: "F",
		shift: "vespertino",
		functionaryId: "712345678",
	},
	{
		section: "6-2",
		grade: "sexto",
		cycle: "II",
		classRoom: "F",
		shift: "matutino",
		functionaryId: "712345678",
	},
];

export default groups;
