const grupos = [
    {
        "seccion":"1-1",
        "ciclo":"2021",
        "grado":"primero",
        "aula":"A",
        "cantAlumno":"0",
        "turno":"true",
        "HorarioId":"1",
        "ProfesorGuia":"712345678"
    },
    {
        "seccion":"1-2",
        "ciclo":"2021",
        "grado":"primero",
        "aula":"A",
        "cantAlumno":"0",
        "turno":"false",
        "HorarioId":"2",
        "ProfesorGuia":"712345678"
    },
    {
        "seccion":"2-1",
        "ciclo":"2021",
        "grado":"segundo",
        "aula":"B",
        "cantAlumno":"0",
        "turno":"true",
        "HorarioId":"3",
        "ProfesorGuia":"712345677"
    },
    {
        "seccion":"2-2",
        "ciclo":"2021",
        "grado":"segundo",
        "aula":"B",
        "cantAlumno":"0",
        "turno":"false",
        "HorarioId":"4",
        "ProfesorGuia":"712345677"
    },
    {
        "seccion":"3-1",
        "ciclo":"2021",
        "grado":"tercero",
        "aula":"C",
        "cantAlumno":"0",
        "turno":"true",
        "HorarioId":"5",
        "ProfesorGuia":"712345676"
    },
    {
        "seccion":"3-2",
        "ciclo":"2021",
        "grado":"tercero",
        "aula":"C",
        "cantAlumno":"0",
        "turno":"false",
        "HorarioId":"6",
        "ProfesorGuia":"712345676"
    },
    {
        "seccion":"4-1",
        "ciclo":"2021",
        "grado":"cuarto",
        "aula":"D",
        "cantAlumno":"0",
        "turno":"true",
        "HorarioId":"7",
        "ProfesorGuia":"712345675"
    },
    {
        "seccion":"4-2",
        "ciclo":"2021",
        "grado":"cuarto",
        "aula":"D",
        "cantAlumno":"0",
        "turno":"false",
        "HorarioId":"8",
        "ProfesorGuia":"712345675"
    },
    {
        "seccion":"5-1",
        "ciclo":"2021",
        "grado":"quinto",
        "aula":"E",
        "cantAlumno":"0",
        "turno":"true",
        "HorarioId":"9",
        "ProfesorGuia":"712345674"
    },
    {
        "seccion":"5-2",
        "ciclo":"2021",
        "grado":"quinto",
        "aula":"E",
        "cantAlumno":"0",
        "turno":"false",
        "HorarioId":"10",
        "ProfesorGuia":"712345674"
    },
    {
        "seccion":"6-1",
        "ciclo":"2021",
        "grado":"sexto",
        "aula":"F",
        "cantAlumno":"0",
        "turno":"true",
        "HorarioId":"11",
        "ProfesorGuia":"712345673"
    },
    {
        "seccion":"6-2",
        "ciclo":"2021",
        "grado":"sexto",
        "aula":"F",
        "cantAlumno":"0",
        "turno":"false",
        "HorarioId":"12",
        "ProfesorGuia":"712345673"
    }
    
]

export default grupos;